# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import airlines_types_pb2 as airlines__types__pb2


class AirlinesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAirline = channel.unary_unary(
        '/Airlines/GetAirline',
        request_serializer=airlines__types__pb2.GetAirlineRequest.SerializeToString,
        response_deserializer=airlines__types__pb2.GetAirlineResult.FromString,
        )
    self.GetAirlines = channel.unary_stream(
        '/Airlines/GetAirlines',
        request_serializer=airlines__types__pb2.NoParameters.SerializeToString,
        response_deserializer=airlines__types__pb2.GetAirlineResult.FromString,
        )


class AirlinesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAirline(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAirlines(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AirlinesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAirline': grpc.unary_unary_rpc_method_handler(
          servicer.GetAirline,
          request_deserializer=airlines__types__pb2.GetAirlineRequest.FromString,
          response_serializer=airlines__types__pb2.GetAirlineResult.SerializeToString,
      ),
      'GetAirlines': grpc.unary_stream_rpc_method_handler(
          servicer.GetAirlines,
          request_deserializer=airlines__types__pb2.NoParameters.FromString,
          response_serializer=airlines__types__pb2.GetAirlineResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Airlines', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
