# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airlines.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import airlines_types_pb2 as airlines__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='airlines.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x61irlines.proto\x1a\x14\x61irlines_types.proto2\x96\x01\n\x08\x41irlines\x12\x45\n\nGetAirline\x12\x1b.airlines.GetAirlineRequest\x1a\x1a.airlines.GetAirlineResult\x12\x43\n\x0bGetAirlines\x12\x16.airlines.NoParameters\x1a\x1a.airlines.GetAirlineResult0\x01\x62\x06proto3'
  ,
  dependencies=[airlines__types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_AIRLINES = _descriptor.ServiceDescriptor(
  name='Airlines',
  full_name='Airlines',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=41,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAirline',
    full_name='Airlines.GetAirline',
    index=0,
    containing_service=None,
    input_type=airlines__types__pb2._GETAIRLINEREQUEST,
    output_type=airlines__types__pb2._GETAIRLINERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAirlines',
    full_name='Airlines.GetAirlines',
    index=1,
    containing_service=None,
    input_type=airlines__types__pb2._NOPARAMETERS,
    output_type=airlines__types__pb2._GETAIRLINERESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRLINES)

DESCRIPTOR.services_by_name['Airlines'] = _AIRLINES

# @@protoc_insertion_point(module_scope)
